buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

group = 'com.github.IamAki123'
version = '1.0.1'

android {
    namespace 'org.firstinspires.ftc.easyobjd'
    compileSdk 34
    defaultConfig { minSdk 24 }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    // Index samples/ in Android Studio without putting them in the release AAR / JitPack.
    sourceSets {
        debug {
            java.srcDirs += ['samples']
        }
    }
}

dependencies {
    compileOnly 'org.firstinspires.ftc:RobotCore:11.1.0'
    compileOnly 'org.openftc:easyopencv:1.7.3'
    testImplementation 'junit:junit:4.13.2'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = project.group
                artifactId = 'EasyOBJD'
                version = project.version
            }
        }
    }
}
